using Microsoft.EntityFrameworkCore.Migrations;

namespace Lab3_Migrations.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Migration code generated by EF Core CLI
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Rollback migration
        }
    }
}